version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '80:8080'
    volumes:
      - ./tmp:/golang-wiki/tmp
    environment: 
      - APP_ENV=${APP_ENV}
    container_name: app
    image: 'roag92/golang-wiki:dev'
