version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '8080:8080'
    volumes:
      - .:/go/src/golang-wiki
    environment: 
      - APP_ENV=${APP_ENV}
    container_name: app-dev
    image: 'roag92/golang-wiki:dev'
