version: '3.7'
services:
  app:
    build:
      target: dev
    ports:
      - '8080:8080'
    volumes:
      - .:/golang-wiki:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment: 
      - app_env=${APP_ENV}
